spring.application.name=gatewayserver

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

#spring.config.import=configserver:http://localhost:8071/
spring.config.import=optional:configserver:http://localhost:8071/

management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=read-only
management.endpoints.endpoint.shutdown.access=unrestricted
management.info.env.enabled=true

eureka.instance.preferIpAddress=false
eureka.instance.hostname=gatewayserver
eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
eureka.client.registry-fetch-interval-seconds=5

spring.cloud.loadbalancer.enabled=true
spring.cloud.loadbalancer.ribbon.enabled=false
spring.cloud.loadbalancer.cache.enabled=false

logging.level.com.bank.gatewayserver=DEBUG