spring.application.name=loans

server.port=8090

#spring.datasource.url=jdbc:mysql://loansdb:3308/loansdb
##spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=root
#spring.datasource.password=root

# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always

spring.config.import=optional:configserver:http://localhost:8071/
#spring.config.import=configserver:http://configserver:8071/

spring.cloud.bus.enabled=false
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

management.endpoints.web.exposure.include=*
management.endpoints.endpoint.shutdown.access=unrestricted

# Eureka Server Configuration
eureka.instance.preferIpAddress=true
eureka.instance.hostname=loans
eureka.client.fetchRegistry=true
eureka.client.registerWithEureka=true
eureka.client.serviceUrl.defaultZone=http://localhost:8070/eureka
#eureka.client.serviceUrl.defaultZone=http://eurekaserver:8070/eureka/
