spring.application.name=loans

server.port=8090

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.data-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

build.version=1.0

# Eureka Service Discovery
eureka.instance.preferIpAddress=false
eureka.instance.hostname=loans
eureka.client.fetchRegistry=true
eureka.client.registerWithEureka=true
eureka.client.serviceUrl.defaultZone=http://eurekaserver:8070/eureka/
eureka.client.registry-fetch-interval-seconds=5

# Spring Cloud LoadBalancer
spring.cloud.loadbalancer.enabled=true
spring.cloud.loadbalancer.ribbon.enabled=false
spring.cloud.loadbalancer.cache.enabled=false

# Springboot profiles

spring.config.import=loans-qa.properties,loans-prod.properties
spring.profiles.active=qa

loans.message=Welcome to EazyBank accounts related local APIs
loans.contactDetails.name=John Doe - Developer
loans.contactDetails.email=john@eazybank.com
loans.onCallSupport[0]=(555) 555-1234
loans.onCallSupport[1]=(555) 523-1345